### ISSUE TITLE
Unable to run python subprocesses (FileNotFoundError)

### ISSUE THREAD

**Issue by FelixFourcolor** [termux/termux-widget#106]
## Problem

It seems that termux widget is unable to run python subprocesses. All attempts to do do so result in `FileNotFoundError`.

## Reproduce

Inside ~/.shortcuts, create two executable files `test.py` and `test.sh`.

test.py: a simple subprocess call
```
#!/bin/python

from subprocess import call

call("/data/data/com.termux/file/home/.shortcuts/test.sh")
```

test.sh: any program will do
```
#!/bin/bash

exit
```

## Expected behavior
Running `test.sh` or `test.py` inside termux is fine. Running `test.sh` through termux widget is fine. It's expected that running `test.py` though termux widget is also fine.

(By "fine" I mean exit normally, because both programs do nothing.)

## Actual behavior
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/.shortcuts/test.py", line 5, in <module>
    call("/data/data/com.termux/files/home/.shortcuts/test.sh")
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 1948, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/home/.shortcuts/test.sh'

[Process completed (code 1) - press Enter]
```

From my investigation, the issue is not related to the fact that `test.sh` is placed inside `~/.shortcuts`. The same error occurs wherever `test.sh` is placed, or for any external program that `test.py` calls. Simply, the path to a python subprocess call is always not found.

## System info
Termux 0.118.0
Termux widget 0.13.0
Android 13
Samsung S22
(Let me know if you need more info)

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-widget#termux-environment

**Comment by FelixFourcolor** [comment]
@agnostic-apollo Woah, thank you for the fast response. I figured it out!

**Comment by agnostic-apollo** [comment]
Welcome.
