### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by Artimidorus** [termux/termux-widget#109]
**Problem description**
On Android 13. When I attempt to install the termux widgets app from FDroid I get an error INSTALL FAILED SHARED USER INCOMPATIBLE.

**Steps to reproduce**
This happens when I download the app either via F-droid app or via browser and attempt to install.

**Additional information**

* Termux application version:
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=3898
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0

* Android OS version:
13.0

* Device model:
Samsung Galaxy Fold 4

**Comment by twaik** [comment]
Install all termux components from the same source.
https://github.com/termux/termux-app#installation

**Comment by Artimidorus** [comment]
Well that was an easier fix than I thought. Thanks. I was sure Samsung had broken things
