### ISSUE TITLE
After update to Termux-0.44 widget scripts crash

### ISSUE THREAD

**Issue by skymoo** [termux/termux-widget#11]
Just updated to Termux-0.44 and now all scripts that I try to run via the widget extension cause Termux to crash, if I connect my phone (Pixel) via adb logcat I get the following around the time of the crash.

http://pastebin.com/cv7fASQd

Reverting to 0.42 gets things working again.

**Comment by fornwall** [comment]
Thanks! This has been fixed in a v0.45 update of the Termux app which has now been released, and should be available as an update shortly. Sorry for the problem!
