### ISSUE TITLE
Google Play Store Wants to Update Termux:Widget Installed From F-Droid

### ISSUE THREAD

**Issue by necopinus** [termux/termux-widget#121]
### Problem description ###

The Google Play Store will attempt (and fail) to update the version of Termux:Widget installed from F-Droid. This is likely because the version of Termux:Widget on Google Play is [0.14](https://play.google.com/store/apps/details?id=com.termux.widget), but the version on F-Droid is [0.13](https://f-droid.org/en/packages/com.termux.widget/).

[Other Termux apps that have been revitalized on the Play Store have received a *pro forma* version bump on F-Droid to address this issue](https://github.com/termux-play-store/termux-apps/issues/8#issuecomment-2160048240), but Termux:Widget has not.

### Steps to reproduce ###

1. Install [Termux](https://f-droid.org/en/packages/com.termux.widget/) and [Termux:Widget](https://f-droid.org/en/packages/com.termux.widget/) from [F-Droid](https://f-droid.org/).
2. Go to (Account) > Manage apps & devices > Updates in the Google Play Store. If necessary, refresh the view.
3. Observe that Termux:Widget is listed as having an update available.
4. Attempt to update Termux:Widget. Observe that the update fails but cannot be hidden.

### Expected Behavior ###

The version of Termux:Widget in F-Droid is in sync with the version in the Google Play Store, such that the Google Play Store does not offer an inapplicable update.

### Additional Information ###

* **Termux application version:** 0.118.1
* **Android OS version:** 14
* **Device model:** SM-S928U1

**Comment by agnostic-apollo** [comment]
#119

**Comment by colmbuckley** [comment]
What happened here? Is a new GitHub/F-Droid release planned, or does the (new) Play Store version of ::widget work fine with the F-Droid version of the main app?

**Comment by colmbuckley** [comment]
(To be clear, I am grateful for the work of the maintainers and developers of these excellent apps, and I'm not trying to be impatient - just a little confused that the "trail has gone dry" here.)

**Comment by agnostic-apollo** [comment]
Read the comments in the linked pull. No, the apps on F-Droid/GitHub and Playstore are not compatible.

**Comment by colmbuckley** [comment]
Thank you. I did read that PR, but thought that the implication was that the ongoing work was being tracked here (hence being confused by "not-planned"). All good!

**Comment by agnostic-apollo** [comment]
Its out, F-Droid will take 5-7 days to release.

https://github.com/termux/termux-widget/releases/tag/v0.14.0
