### ISSUE TITLE
Launcher to Termux without script

### ISSUE THREAD

**Issue by NoNameWasDefined** [termux/termux-widget#123]
**Feature description**

Sorry for my bad english
Above the shortcuts there is a label Termux, I wish that this label can start a session by default of Termux.

**Comment by agnostic-apollo** [comment]
Create a script that runs `$PREFIX/bin/login` with `RUN_COMMAND` intent.

https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent#top-command-with-am-startservice-command

The widget title is meant to launch Termux:Widget app launcher activity.
