### ISSUE TITLE
Removing or replacing the "tasks/"

### ISSUE THREAD

**Issue by NoNameWasDefined** [termux/termux-widget#124]
**Feature description**

Sorry for my bad english.
For each shortcut it is displayed the location of the script from "~/. shortcuts", which applies to the tasks.
I think that for the tasks it should not be displayed "tasks/" before the name of each task or as something else indicates otherwise.

**Comment by agnostic-apollo** [comment]
`tasks/` is for a directory hierarchy, there could be other sub directories too other than `tasks`. Anyway in a future version users will be able to select a custom directory whose scripts are run as tasks directly.
