### ISSUE TITLE
Play store constantly tries to update to 14 if f-droids 13 is installed

### ISSUE THREAD

**Issue by kevlar700** [termux/termux-widget#129]
**Problem description**
If you install from the play store then access to .shortcuts does not work as termux is installed from f-droid.
If you install from f-droid then it has access to .shortcuts and works. However play store sees itself as having a newer version 0.14 and constantly tries to update the widget and failing to do so.

**Steps to reproduce**
Install termux from f-droid
Install termux-widget from f-droid

**Expected behavior**
No apps needing updating in play store

**Additional information**

* Termux application version: Termux:0.118.1 Widget:0.13.0
* Android OS version: 14
* Device model: Samsung Xcover5

**Comment by kevlar700** [comment]
I wonder why my search skills failed. Okay will close it now. It is more of an annoyance than a real problem.

**Comment by colmbuckley** [comment]
@agnostic-apollo maybe leave one of these open so people don't keep filing dupes, WDYT?

**Comment by TomJo2000** [comment]
We can mark issues as duplicates regardless if the original is open or closed.

**Comment by jasttw** [comment]
Can we please have an update on this issue? It has been over 6 months since the update was pushed on Google Play and we still have it on the available updates with it failing to install and no updates on GitHub or fdroid. I really hope someone can give this some time and push an update for us

**Comment by colmbuckley** [comment]
@agnostic-apollo I guess you haven't had time to get this sorted out? Is there any room for a minimalist fix, changing only the version number? 

Is there anything I can do to help?

**Comment by agnostic-apollo** [comment]
I finished the changes for release a couple of days ago, have to write changelog and stuff, will make a release within next couple of days.

**Comment by colmbuckley** [comment]
You're a star, thank you!

**Comment by agnostic-apollo** [comment]
Its out, F-Droid will take 5-7 days to release.

https://github.com/termux/termux-widget/releases/tag/v0.14.0
