### ISSUE TITLE
How in install colorll in termux

### ISSUE THREAD

**Issue by DHANAVATHgANESH** [termux/termux-widget#132]
![Screenshot_20241225_143455_YouTube](https://github.com/user-attachments/assets/48549bc8-3143-4cb0-a859-203135958a44)

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:
* Android OS version:
* Device model:

**Comment by twaik** [comment]
https://github.com/termux/termux-community/blob/site/site/pages/en/rules/hacking.md
