### ISSUE TITLE
All Shortcuts widget crashes after update to Termux 0.54

### ISSUE THREAD

**Issue by skymoo** [termux/termux-widget#17]
Since updating to Termux 0.54 trying to run a script from the All Shortcuts widgets cause an error to pop up sating that Termux-Widget has crashed. After that the widget stops working and I need to remove it and add it again. Initially the scripts run as expected but after a short time the same happens.

This is on a Pixel 2.

**Comment by h6y3** [comment]
I have a similar issue on the Pixel 2 XL.  My scripts may work initially but after a period of time, I get a Force Close and I have to remove the widget and re-add just so it can work one time.

I really hope this can be addressed as I had gotten quite fond of launching scripts from the widget.

**Comment by fornwall** [comment]
I screwed things up - looking at it!

**Comment by fornwall** [comment]
@skymoo @h6y3 Thanks a lot for reporting! This problem has been fixed in version 0.8 of the Termux:Widget app, which should be available as an update from Google Play in a few hours (and from F-Droid in a day or two).
