### ISSUE TITLE
Termux-widget not starting termux 

### ISSUE THREAD

**Issue by KopiasCsaba** [termux/termux-widget#18]
If i press on any shortcut on the widget, it does not open termux (cold start).
But if i open termux, and leave it and then click on any shortcut, it opens up and runs fine.

Let me know how can i help debug it more for you!

Thanks for termux!

**Comment by fornwall** [comment]
Are you using the latest Termux:Widget version (v0.8)? If so, which Android version are you running?

**Comment by KopiasCsaba** [comment]
Thank you for responding!

So no, i'm using it from F-droid, and they have Termux 0.54 & Termux:Widget 0.7.
I'm on LineageOS 14.1 that means Android 7.1.2!

**Comment by GriDevE** [comment]
Same problem on new phone with MIUI and Android 11.
Everything works fine on an old phone with MIUI and Android 10.
Termux-widget v0.11 from Google Play.

**Comment by agnostic-apollo** [comment]
@GriDevE Disable battery optimizations and enable autostart as per https://dontkillmyapp.com/xiaomi and grant `Termux` app [Draw over apps](https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent#draw-over-apps-permission-optional) permission.
