### ISSUE TITLE
Problem running Frotz

### ISSUE THREAD

**Issue by dalb8** [termux/termux-widget#2]
If I execute frotz Trinity.z4 I'm fine but if I launch it via a widget I get : "[Screen too narrow] [Hit any key to exit ]. I've tried setting the screen and script widths as Frotz options and zooming termux but nothing works. 

Nexus 7 Android 6 Custom ROM.

**Comment by fornwall** [comment]
Can you check if it starts working with a `sleep 1` at the top of the script you launch with the widget?

This is probably a problem with the main Termux app, in that it does not give a correct terminal size to processes directly, but starts with a dummy 20x20 terminal and then updates the terminal size once layout has been done. Most "modern" terminal programs adjust to the terminal size at runtime, but frotz seem to be more stuck with the initial size.

**Comment by dalb8** [comment]
That doesn't work


-------- Message d'origine --------
De : Fredrik Fornwall <notifications@github.com>
Envoyé : 7 février 2016 23:38:26 GMT+00:00
À : termux/termux-widget <termux-widget@noreply.github.com>
Cc : dalb8 <daithi_black@yahoo.ie>
Objet : Re: [termux-widget] Problem running Frotz (#2)

Can you check if it starts working with a `sleep 1` at the top of the script you launch with the widget?

This is probably a problem with the main Termux app, in that it does not give a correct terminal size to processes directly, but starts with a dummy 20x20 terminal and then updates the terminal size once layout has been done. Most "modern" terminal programs adjust to the terminal size at runtime, but frotz seem to be more stuck with the initial size.

---

**Comment by fornwall** [comment]
This should be fixed by the v0.28 update of the main Termux app, which should be available as an update in the Play store or F-Droid shortly! Re-open this issue if the problem remains after updating Termux to 0.28.
