### ISSUE TITLE
Shortcut doesn 't work with KISS Launcher

### ISSUE THREAD

**Issue by jsparber** [termux/termux-widget#3]
The shortcut dosen't work with the [KISS Launcher](https://f-droid.org/repository/browse/?fdfilter=kiss&fdid=fr.neamar.kiss). With KISS other shortcut maker work (like Any Cut or firefox bookmarks).

**Comment by fornwall** [comment]
How do I create a shortcut using the KISS Launcher?

**Comment by jsparber** [comment]
You can not create a shortcut directly in KISS, but with Any Cut you can create a shortcut through the app the same as for Firefox.

**Comment by adbenitez** [comment]
having this problem also, when I choose to add widget only the widget of the shorcuts list is shown, anyway widgets are beta in KISS and seems like you can only add one widget. I have tried to add a shorcut from Ghost Commander and it doesn't work also :-/
