### ISSUE TITLE
Cannot install Termux:Widget on ASUS_Z011D with Android 6.0.1

### ISSUE THREAD

**Issue by linux-player9** [termux/termux-widget#32]
Hey ! I tried to install Termux:Widget with F-droid on my ASUS_Z011D phone running Android 6.0.1 and it failed to install. Termux was closed when I tried and the error message don't give any details.

**Comment by xeffyr** [comment]
Are you mixing Google Play & F-Droid installations ?

**Comment by eadmaster** [comment]
can we have a free version on the play store?

**Comment by linux-player9** [comment]
You can install Termux and Termux:Widget for free on F-Droid.

**Comment by eadmaster** [comment]
ok, but unfortunately i cannot install the F-droid version without uninstalling the GPlay version first (and losing all the current app data)...

**Comment by fornwall** [comment]
@eadmaster Sorry for the late reply here, but the best way to migrate between GPlay and F-Droid is probably to take a backup of your `$HOME` directory (such as zipping it and putting the zip file on the SD card, or e.g. mail it).
