### ISSUE TITLE
Disable "Task executed: NAME-OF-SCRIPT.sh" toast when running a task via widget

### ISSUE THREAD

**Issue by mwcarew** [termux/termux-widget#33]
```shell
#!/bin/bash

SSID="$(termux-wifi-connectioninfo | jq -r .ssid)"

if [ $SSID = "blahblah"]; then
  termux-toast Pihole disabled successfully.
else
  termux-toast Not connected to home WiFi.
fi
```

I use toasts to get the results of my script, but termux-widget does a "Task executed: NAME-OF-SCRIPT.sh" toast first and I have to wait for that to disappear before seeing the results. Super minor issue but I'd love for it to be a hair faster and be able to disable that initial toast.

**Comment by mwcarew** [comment]
```java
		Intent executeIntent = new Intent(TermuxWidgetProvider.ACTION_EXECUTE, scriptUri);
		executeIntent.setClassName("com.termux", TermuxWidgetProvider.TERMUX_SERVICE);
		if (clickedFile.getParentFile().getName().equals("tasks")) {
			executeIntent.putExtra("com.termux.execute.background", true);
			// Show feedback for executed background task.
			String message = "Task executed: " + clickedFile.getName();
			Toast toast = Toast.makeText(this, message, Toast.LENGTH_SHORT);
			toast.setGravity(Gravity.CENTER, 0, 0);
			toast.show();
		}
```

I'm not familiar with Java but I see where the relevant code is in [TermuxLaunchShortcutActivity.java](https://github.com/termux/termux-widget/blob/master/app/src/main/java/com/termux/widget/TermuxLaunchShortcutActivity.java). I like how the default behavior is to confirm the task has run.

I'm not sure how I'd change it myself if I wanted to add this feature.

**Comment by fornwall** [comment]
Thanks for the suggestion!

As an easy fix I change the "Task executed" toast to be on the top of the screen, to not block toasts from termux-toast (which are by default shown in the center of the screen).
