### ISSUE TITLE
cannot run gcloud from widget

### ISSUE THREAD

**Issue by jaroslaw-weber** [termux/termux-widget#34]
```
#!/data/data/com.termux/files/usr/bin/sh
gcloud compute start instance games
```

This is my script but it's not working.
I get 

 gcloud: not found

error.

The script is working if run the command in normal termux mode.

What is wrong with my script?

**Comment by xeffyr** [comment]
Use absolute paths for custom binaries.

**Comment by resistdesign** [comment]
> Use absolute paths for custom binaries.

Holy crap! Super inconvenient.

**Comment by xeffyr** [comment]
> Super inconvenient.

So, how Termux:Widget should find all user's custom binaries ? Termux:Widget doesn't launch shell to execute scripts, it execute them directly instead.

Want something at custom PATH, then modify PATH environment variable in your script in way you want.

**Comment by resistdesign** [comment]
Best bet is to run as the user that runs the termux app or at least give the option to.
