### ISSUE TITLE
Termux:Widget scripts now closing the session directly without prompting to close

### ISSUE THREAD

**Issue by LaChirla** [termux/termux-widget#35]
After the latest ugprade Termux:Widget and Termux is not working the same way like before.
If a script only outputs an info, before I had to close the opend session manually.
Now, after the upgrade, the session closes directly after ending, so I can't read the output. Of course, "read x" or similar  at the end of the script keeps it open. But ...
How can I get back the old behavior?
Thank you.

termux version: 0:72
termux:widget version: 1.0

**Comment by xeffyr** [comment]
That's intended behaviour.

If you don't want to close session automatically, you need to prompt for user input manually. In bash you can achieve this with following command:
```
read -p "Press enter..."
```

**Comment by LaChirla** [comment]
Thanks for the reply, so I'll update all my scripts.
