### ISSUE TITLE
Scripts started from widget cannot execute other scripts

### ISSUE THREAD

**Issue by EnsignCrasher** [termux/termux-widget#37]
I'm trying to run scripts on /storage/emulated/0 from the widget and as symlinks did not work I tried to "meta-script" in .shortcuts with starts my script in /storage/emulated/0.
Thereby I noticed ,if you run a script in .shortcuts through the termux-widget, it will always tell "file not found" when accessing other files.

so here are the steps to reproduce to make  it clearer:
.shortcut/test.sh:
```
#!/bin/sh
path="$(cd "$(dirname "$0")" && pwd)/test2.sh"

$path

ls -lah "$path"

sleep 10
```

.shortcut/test2.sh
```
#!/bin/sh
printf "hello world\n"
```

then  run:
```
chmod +x .shortcut/test.sh
chmod +x .shortcut/test2.sh
```

and then execute test.sh in termux-widget

error when executing the script: [path-to-test2.sh] not found
ls will show that the file exists

if you run the scripts from the command line it will work as well

**Comment by xeffyr** [comment]
Replace
```
#!/bin/sh
```
with
```
#!/data/data/com.termux/files/usr/bin/sh
```

**Comment by xeffyr** [comment]
You cannot use "standard" shebangs with widgets.
