### ISSUE TITLE
widget behavior for several tables

### ISSUE THREAD

**Issue by RalfWerner** [termux/termux-widget#39]
**Feature description**
@xeffyr With `mv .shortcuts widget` I changed the path, connected again with the symlink:
`w=widget; s='~/.shortcuts'; ln -s $w $s` and split my entries in 3 paths (termux `~/$w`, ubuntu `uu/$w` and sdcard/proot `i/$w`). Then I add the entries:
`cd uu/$w; echo"s=$s; rm $s; ln -s ~/$w $s">' termux-widget'` and
`cd ~/$w; echo "s=$s; rm $s; ln -s ~uu/$w $s">' ubuntu-widget'` (same for `sdcard`).
So nothing has changed on the startscreen except for the first (two) action (replaces the symlink with shortcuts that are possible in _ubuntu_ and _proot_) and now it looks like this:
![grafik](https://user-images.githubusercontent.com/45426380/74056109-a3a21880-49e1-11ea-8785-8a9a82301b5b.png)
I started processes from all tables, which are managed in the Navigator (shot4).

What I expect is to have a _**changed table**_ on the start screen (shot2/3) by tapping the second action (shot1). However, this is _**only**_ the case, if _**no**_ termux-bash is open and after I have tapped _**reload**_.
Could this be realized by a _specific_ exit number, such as `exit 1` (received the navigator entry) - _**no switch and reload?**_

[Continued](https://github.com/termux/termux-packages/issues/2107#issuecomment-599543660) from our dialog about _Studio_ test environment with API/widget with **Q10/R11** emulators:
> install Termux:API but not run it ... Just added in per-repository mode.

To your @xeffyr last topic `mv wd/te*/*/dev* wc/.android` would be _**ok - or better not?**_
```
WSL[AS/x]$ ll wd/te*/*/dev* wc/.android/deb* wd wc
lrwxrwxrwx 1 th80wr th80wr   19 Mar 12 09:48 wc -> /mnt/c/Users/th80wr
-rwxrwxrwx 1 th80wr th80wr 2105 Mar 14 12:45 wc/.android/debug.keystore
-rwxrwxrwx 1 th80wr th80wr    0 Mar 14 12:45 wc/.android/debug.keystore.lock
lrwxrwxrwx 1 th80wr th80wr   18 Mar 12 09:04 wd -> /mnt/d/Android/App
-rwxrwxrwx 1 th80wr th80wr 2097 Mar  6 16:10 wd/termux-api/app/dev_keystore.jks
-rwxrwxrwx 1 th80wr th80wr 2097 Mar  6 16:10 wd/termux-app/app/dev_keystore.jks
-rwxrwxrwx 1 th80wr th80wr 2097 Mar  4 17:23 wd/termux-widget/app/dev_keystore.jks
-rwxrwxrwx 1 th80wr th80wr 2097 Mar  6 16:10 wd/termux-x11/app/dev_keystore.jks
```
Installation of the API plugin in Studio. **Shot1:** the build actions of the first three parts generate the APK and install it on the current emulation (here Q10). **Shot2:** the `*.apk` is created with _Build Bundle._ **Shot3:** after drag & drop from PC Explorer, the plugin is also included in the emulation. **Shot4:** Start screen with the widget table from which _dialog API_ is started and then displayed in **Shot5** - here with the emulated phone functions on the right. In **Shot6** the process can be seen in the Navigator (if no _dialog_ is active anymore). The _sensor_ analysis runs in the background.
![grafik](https://user-images.githubusercontent.com/45426380/76957400-06a69980-6916-11ea-9643-230f819a874c.png)
Unfortunately the API installation is more complex than for the other plugins and there are a few problems that I have reported in [paste](https://github.com/termux/termux-app/issues/978) or only occur in the emulation:
- Dialogues and navigator (drawer) can _**not**_ be displayed at the _**same time.**_ Here I use a _while loop,_ which enables cell phone rotation (termux-dialog _interrupt_ the action, as with _drawer_). Starting multiple times is also problematic if dialogues are held at the same time. But also possible parallel actions (_sensor/selfie_) lead to _**stalled problems**!_
- The action _selfie_ creates a `~/tmp.jpg` file and ends the widget action with `exit 1`, which is not done with the camera during emulation (my inexperiance). The image could edited with `termux-open tmp.jpg` before `exit 1`.
- The action _speech_ should have a written&acoustic dialogue with you and the phone/emulator. This is no problem on the _real device._ It's funny to count up 1-9 in different languages ​​and what the _recognition_ does with it. Unfortunately, the process _often_ does not come to a conclusion (stalled) as can be seen in the process control (**Shot1** below) and can only be stopped with `pkill termux-api`.

The following **Shot1** shows the processes _during **dialog API**_ action (stalled: 18005,19202) and **Shot2** the script (extract from `sd/ip/bashrc`). **Shot3** is the _first try_ (strings only) widget via Studio [adjust](https://github.com/termux/termux-widget/blob/master/app/src/main/res/values/strings.xml)
![grafik](https://user-images.githubusercontent.com/45426380/76957516-39509200-6916-11ea-828c-2c2e2fa98795.png)
You added _feature request_ to this repo. Would _**this be a suitable case**_ (I use _**Studio**_ or signed all `*.apk` with _my_ private keystroke) _**to use it?**_

**Comment by RalfWerner** [comment]
With the widget version 0.13 `.shortcuts` is no longer allowed as a _**symlink**_. Also symlinks in this path are now prohibited. The idea of **this issue** ​​managing a widget table with a data object, which has not been a problem so far, is so no longer possible in this way.
As a reasoning writes @agnostic-apollo 
> It's not a bug, it's intentional behaviour. The canonical path of all scripts must be under ~/.shortcuts, I'll make it more clear in README. You can create hidden directories under it like ~/.shortcuts/.ubuntu and replace the contents of ~/.shortcuts (except the hidden directories) with that of a specific hidden directory dynamically. That should work.

Since there was _**no problem so far**_, the justification does not light up to me. Also why symlinks on paths are treated differently than paths themselves is _very unusual_ for `bash`. Now you has cemented this [behavior](https://github.com/termux/termux-widget/commit/0a7130f7baee8768084ee81324e2ed31e3175e54) and you does not seem to dissuade your idea.
So _canonical path_ means _**symlinks forbidden!**_
Maybe I'm not the only one like the _**simple switch**_ between widget tables and others also complain the loss and would like to behave normal bash. So I'm waiting for further issues before I do:

For object widgets, a more complicated procedure is to choose and I have to rewrite widget on all my devices.
I had hoped with this issue  to get a _**simple procedure**_ analogous to `exit 1` for _confirm_ (e.g., `exit 2`) for the _refresh_.

Instead, the _refresh toast_ has been extend by an `<id>`, if tap _manually_ on  Reload Buttom, that must be _edited manually_ in the [documented](https://github.com/termux/termux-widget/commit/0a7130f7baee8768084ee81324e2ed31e3175e54) `am ...` action inside the widget action _script_. So refresh _without manual_ refresh buttom, can only be done _by manual_ refresh. I checked that on two devices and got two different `<id>`.
_**Could you also describe a way that determines the `<id>` by this script?**_ Please answer here!

**Comment by agnostic-apollo** [comment]
> So canonical path means symlinks forbidden!

It's forbidden for `termux-tasker` too for almost a year now.

>Could you also describe a way that determines the <id> by this script?

The id is not decided by `termux-widget` but by the launcher (maybe android) and will be different for each widget created on each device. There is no way to get it from a script, unless you use `root` access to get it from the launcher db, but you probably won't be able to know which entry is for which widget if multiple widgets exist. Maybe in future termux can store the ids internally when it receives them and refresh all widgets at once. That can be looked into in future, I haven't looked much into how widgets  work.

**Comment by RalfWerner** [comment]
> It's forbidden for termux-tasker too for almost a year now.

Ok! Thanks for responding `termux-tasker` I_ve checked only rough. Above I've extend the _two lines example_ with some more questions - _**any Idea to that?**

**Comment by RalfWerner** [comment]
The `am ...` function behind `reload.Style` in Termux is also executable _**via script**_ (`termux-reload-settings`). Could a comparable process be inserted in the widget app to avoid the `<id>` problem and reduce  _"canonical"_ to `$s/task`?
If so, I would like to have passed the name of the table as [above](https://user-images.githubusercontent.com/45426380/76957516-39509200-6916-11ea-828c-2c2e2fa98795.png) as a parameter.

**Comment by agnostic-apollo** [comment]
With bcb0ab6c, the canonical path can be under `~/.termux`. You should be able to do whatever you were doing before by moving directories under `~/.termux`. I don't have time to understand it. This change will also be helpful  if and when main directory is changed to `~/.termux/widget` from `~/.shortcuts`, with backward compatibility.

> So all these icon-shortcuts must recreate with 0.13 version?

Read the [`v0.13.0` changelog](https://github.com/termux/termux-widget/releases/tag/v0.13.0), its written in **bold**.

>A widget source analysis shows: last 34, this morning 32 and less before. In the changed 4,6 sources I have not found anything like that.

I am not sure why your launcher would change it, but as I said, such problems will be looked into in future with a possible "refresh all" option.

**Comment by RalfWerner** [comment]
> The canonical path can be under `t=~/.termux`. You should be able to do **whatever you were doing before**

Than would be `ln -s  .termux/widget ~/widget` [valid](https://github.com/termux/termux-widget/issues/39#issue-561814981), but is'nt! Two reasons: **first** `$t` still must be _canonical_ (check impossible) and **secondly** shortcuts in `$t` are not taken into account in the widget table. If I remove `s=.shortcuts`, _refresh_ newly created it, even if `$t/widget` exists with _canonical_ shortcuts. _**Dit I somethig wrong?**_
> I am not sure why your launcher would change it ...

Mostly I use _selfbuild_ `*.apk`, whose source I get with `git clone ...` locally, after I saved the last version. `diff -r ...>1` is then README+[your commit](https://github.com/termux/termux-widget/commit/bcb0ab6cf1b72dfb16ed9b48a9e291bab438d3ea) as file. That I call here **widget sources analysis** and has now again 34 sources (`find -type f|wc -l`), in which 6 sources are changed (`grep -c diff 1`). 
With `grep "/.termux" 1` I get the **two lines** in README and also not more, when I search in all sources. _**How/where should the switch from `$s` to `$t` be done in sources?**_

**Comment by agnostic-apollo** [comment]
If you want scripts in `~/.termux` to show, create a symlink for them inside `~/.shortcuts`, like  `ln -s ~/.termux/script ~/.shortcuts/script`. I am not going to spend time trying to understand whatever you are trying to do and say. You probably want to create multiple widgets, each with its own directory. That can be added in future and is not supported currently. Wait till its implemented.

You are "probably" looking for this https://github.com/termux/termux-widget/blob/v0.13.0/app/src/main/java/com/termux/widget/TermuxWidgetService.java#L20

**Comment by RalfWerner** [comment]
> **That** can be added **in future** and is not supported currently. Wait till its implemented

My problem is _**That**_ currently (0.13) does **not work _anymore_**! At 0.12 (this Issue) I've described **How _That_ works** but _**refresh**_ is the topic of this issue. To this, you have a cumbersome workaround (no problem) that open termux each time (unsightly and should affect Startscreen only).
>... or for a whole directory with `ln -s ~/.termux/dir ~/.shortcuts/dir`.

Did you ever check that? Of course it does **not work** because of _**Canonical**_

**Comment by Grimler91** [comment]
@RalfWerner I also do not understand what the issue is, or what the feature that you are requesting is. Please open a new issue or feature request and fill in the info requested in the [bug report template](https://github.com/termux/termux-widget/issues/new?assignees=&labels=&template=bug_report.md) or the [feature request template](https://github.com/termux/termux-widget/issues/new?assignees=&labels=&template=feature_request.md), **in a concise manner**. 

For the best result I think you can leave out all bold text, all italic text, and avoid concatenating screenshots

**Comment by agnostic-apollo** [comment]
>That currently (0.13) does not work anymore! 

The only thing that doesn't work is trying to put symlink files that target files outside `~/.shortcuts` or `~/.termux`.

>Did you ever check that?

Yes, I did.

>Of course it does not work because of Canonical

It seems you don't under the meaning of canonical path. The `ln -s ~/.termux/dir ~/.shortcuts/dir` command will create a symlink file at `~/.shortcuts/dir` that points to the directory at `/data/data/com.termux/files/home/.termux/dir` which is under `~/.termux` and is an allowed path. If you were trying to create the symlink like `ln -s .termux/widget ...` mentioned above without `~/` at the start which is expanded by the shell, then that will create a dangling pointer that doesn't point to anything and is not a valid path. I am not here to fix your shell scripting mistakes.

**Comment by RalfWerner** [comment]
>  Did you ever check that? **Yes, I did.**

I've also just now checked again with 0.13 and the same effect. What is the _**difference between our checks?**_
Ive checked on two real devices and one AVD. with Android 9 and 11.
