### ISSUE TITLE
Can't execute silently, you must click into the termux app

### ISSUE THREAD

**Issue by zixijian** [termux/termux-widget#42]
**Problem description**

Can't execute silently, you must click into the termux app。

**Steps to reproduce**

I wrote a script to clean up phone junk files and put it in $HOME/.shorcuts/.
Then I added controls on the Android desktop.
Then I clicked on the script and the termux notification appeared in the notification bar, but the script did not start execution.
When I click the app script from the notification bar to execute it, I exit. Clicking the app and opening the app in advance are the same result. It must be entered to execute.

**Expected behavior**

I want to know how to perform silently.

**Additional information**

* Termux application version:0.94
* Termux widget version:0.11
* Android OS version:10
* Device model:Redmi Note 7 Pro

**Comment by agnostic-apollo** [comment]
Grant `Draw Over Apps` permission to termux. https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent#draw-over-apps-permission-optional

And install updated version of termux from F-Droid, it would show a warning if permission is missing. https://github.com/termux/termux-app#google-playstore-deprecated
