### ISSUE TITLE
support for minimalist launchers

### ISSUE THREAD

**Issue by cauerego** [termux/termux-widget#44]
**Feature description**

i'm using niagara. it only allows for 1 widget, for good reasons.

could you please add some option to either add application shortcuts (so each script would be like a web page shortcut) and or app action (like "termux new session")?

thanks for these amazing tools around termux!

**Comment by xeffyr** [comment]
Do you need application shortcuts for app or widget? Application already has shortcut for starting new session.
Regarding Termux:Widget - have you tried the "big" variant which is a list of scripts?

**Comment by cauerego** [comment]
big variant?

i just want a shortcut for the scripts which isn't a widget... using "application shortcut" was only a suggestion. 😁
