### ISSUE TITLE
only 1x1 widget available on Android 10

### ISSUE THREAD

**Issue by readyblue** [termux/termux-widget#45]
Hi, there seems to be some problem with Termux Widget on Android 10, only widget 1x1 is available, nothing bigger and that is shame.

Can you please take a look?

Thanks

**Comment by UltraBlackLinux** [comment]
Usually you can resize stuff like that; A long press on the wiget then release and drag the dots on the sides

**Comment by readyblue** [comment]
I have figure it out. Termux Widget app needs to be installed on internal storage. I have moved it from external (default when you have your SD card formated as internal storage) to internal and list widget (resizable one) finally appear in the menu. I know that Termux needs to be installed on internal storage, now I know that Termux Widget needs to be there as well.

**Comment by agnostic-apollo** [comment]
Widgets do not show if installed app is installed on external sd card as per android policy https://developer.android.com/guide/topics/data/install-location.html#ShouldNot.
