### ISSUE TITLE
Only 2x2 widget on Android 10

### ISSUE THREAD

**Issue by timonoko** [termux/termux-widget#52]
**Problem description**
I am getting only the 2x2 widget, which is a listing of all .shortcuts. 

**Steps to reproduce**

**Expected behavior**
Individual 1x1 widgets for some important shortcuts.

**Additional information**

* Termux application version:
* 0.116
* Android OS version:
* 10
* Device model:
* Xiaomi M2006C3LG
* There are other 1x1 widgets in the menu, like "Open Camera: Take  Photo". But most other 1x1 widgets have disappeared. Definitively something wrong with this phone.

**Comment by timonoko** [comment]
This phone is def

**Comment by timonoko** [comment]
Problem solved. With "Shortcut Maker" --> "In App" you can choose an item in Termux-widget list and even  make fancy  new icon for it.

**Comment by miluoshi** [comment]
I have the same problem. Using additional app is only a workaround, not a solution. This issue should be reopened.

Termux version: 0.117
Android 11
Device: Realme 7 pro (RMX2170)

**Comment by agnostic-apollo** [comment]
`2x2` is only the default size of the widget, your launcher should have a way to resize the widget. In nova launcher, you long hold the widget and use `Resize` option. Working fine on android `7` and android `11`. And stuff like Shortcut Maker will probably not work in [version `>= 0.13.0`](https://github.com/termux/termux-widget/releases/tag/v0.13.0). Old shortcuts have also been invalidated and will need to be recreated.
