### ISSUE TITLE
Sometimes the widget stops to work

### ISSUE THREAD

**Issue by RigacciOrg** [termux/termux-widget#56]
**Problem description**
After some time of usage the widget suddendly stops working. Pressing the reload icon does not longer show the "Termux shortucts reloaded" toast. Tapping anyone of the items does not start the relevant script. Sometimes the list of items resets itself, displaying the "No files in $HOME/.shortcuts/" .

- This is not the same of issue [#18], because having an open Termux terminal does not solve the problem.
- Removing the widget and re-adding it does not solve: the only workaround seems to be a reboot.
- I have added the permission to drawing over other apps to Termux.
- I have removed battery optimization from Termux

**Steps to reproduce**
Boot the phone, normal use for half a day or so.

**Expected behavior**
Termux-widget works always.

**Additional information**

* The phone is running the Rootless Pixel Launcher version 3.9.1 as the home app, installed from F-Droid. The stock Android 11 provides Quickstep instead. Switching the home app from Rootless Pixel Launcher to Quickstep does not revive the widget.
* The phone is rooted with Magisk Systemless Rooting.

* Termux application version: Termux-widget 0.12, Termux app 0.117 both from F-Droid
* Android OS version: 11
* Device model: Oukitel WP12

**Comment by RigacciOrg** [comment]
It turned out that the problem is caused by the **DuraSpeed** settings in my phone (Oukitel WP12 with Android 11). That setting is intended to limit the background processes, I suppose to increase battery life and reactivity of foreground app. Unfortunately it causes the Termux Widget to stop working after some time.
DuraSpeed can be configured accessing the Settings menu: I tried to **disable DuraSpeed** for **Termux**, **Termux:Boot** and **Rootless Pixel Launcher**, but this does not fix the problem.
The only solution that worked for me was to **disable DuraSpeed at all**.

**Comment by agnostic-apollo** [comment]
I have added a launcher icon/activity that can optionally be disabled with 7c7612a8. Try version [`0.13.0`](https://github.com/termux/termux-widget/releases/tag/v0.13.0) when its released on F-Droid https://github.com/termux/termux-app#Installation. It may solve the issue.

**Comment by RigacciOrg** [comment]
From F-Droid, I upgraded Termux:Widget to version **0.13.0**. Now I can enable the DuraSpeed option from phone settings and I can list Termux:Widget as an exception: **the problem is solved** and everything works as expected. Thanks!

**Comment by agnostic-apollo** [comment]
Great, you are welcome.
