### ISSUE TITLE
Script doesnt work through the termux widget but works perfectly fine through termux

### ISSUE THREAD

**Issue by msr8** [termux/termux-widget#61]
**Problem description**

For some reason, when I put the following script in the `~/.shortcuts` folder and try to run it through the termux widget, it gives me the error `read: Illegal option -n` although it works fine when I do `bash ~/.shortcuts/trial.sh`
```
neofetch
read -n 1 -s
```
![WhatsApp Image 2021-11-10 at 9 52 15 AM](https://user-images.githubusercontent.com/79649185/141063031-1ba1df3c-6ec7-412e-b54a-9a9dac9429a3.jpeg)
![WhatsApp Image 2021-11-10 at 7 16 15 AM (1)](https://user-images.githubusercontent.com/79649185/141063063-6b223040-8b37-4d85-a8bf-0d557b95d4e0.jpeg)

**Steps to reproduce**

Make a file trial.sh in `~/.shortcuts` containing the given code and try to run it through the termux widget

**Expected behavior**

It is expected to run the command `neofetch`, wait for a keystroke, and then exit the program

**Additional information**

* Termux application version: 0.117
* Android OS version: 9
* Device model: Redmi Note 6 Pro

**Comment by Grimler91** [comment]
Set a shebang. Right now it is using /system/bin/sh and read from that shell is not as functional as termux's bash

**Comment by msr8** [comment]
I am afraid I am an absolute beginner and I don't know what a shebang is or how to create it, can you please point me in the right direction?

**Comment by Grimler91** [comment]
Add `#!/data/data/com.termux/files/usr/bin/bash` as the first line. Then termux's bash will be used for interpreting the script, instead of android's default shell (`/system/bin/sh`). See also https://en.wikipedia.org/wiki/Shebang_(Unix)
