### ISSUE TITLE
Run commands in headless mode

### ISSUE THREAD

**Issue by EnriqueWood** [termux/termux-widget#65]
I don't know if this can or not already be done, but I couldn't find a way to achieve it.

It would be nice if you could mark a script or widget to run in headless mode, that is, not bringing Termux to foreground, just executing the command and -maybe- showing a toast with the result of the execution

**Comment by xeffyr** [comment]
That's already supported. Just move your script to `~/.shortcuts/tasks`, create widget and your script should run in background. However the toast message doesn't show the result of execution, just notifies that task was executed.

**Comment by agnostic-apollo** [comment]
`termux-toast` or `termux-notification` can be used to show the result.

https://wiki.termux.com/wiki/Termux-toast

https://wiki.termux.com/wiki/Termux-notification
