### ISSUE TITLE
Termux script shortcut triggers device hang

### ISSUE THREAD

**Issue by Minabsapi** [termux/termux-widget#67]
## Problem description

Upon launching a script through the Termux:Widget module, the script fails and the device starts hanging, apparently due to a memory leak
**That script when launched directly through Termux doesn't trigger any issue**

## Steps to reproduce

1. Create this script in Termux 's ".shortcuts" folder

**Toggle ADB**
```bash
getprop init.svc.adbd | grep "running" && (sudo stop adbd) || (sudo start adbd)
```
Its effect is to toggle device's ADB Daemon on / off according to its state.

2. Start it from Termux (not shortcut) to see for yourself this works as intended (if rooted).

3. Create a new shortcut targeting it

## Expected behavior

Should work as it would when launched directly through the Termux app

## Actual behavior
`stop` will fail, and the device will start to hang a few seconds after

[Screenshot](https://imgur.com/a/Tve8xeW)

## Additional information

* Termux application version: 0.117
* Termux:Widgets version: 0.13.0
* Android OS version: 8.1.0
* Device model: Xiaomi Mi A1

**Comment by agnostic-apollo** [comment]
Working fine for me. Are you using `sudo` from `tsu` package? If yes, then remove it with `apt remove tsu` and try latest version of [this `sudo`](https://github.com/agnostic-apollo/sudo) instead and check if it works.

Seems like some environmental issue.

https://github.com/termux/termux-widget#termux-environment

**Comment by Minabsapi** [comment]
I was indeed using `sudo` from the `tsu` package. Removed and replaced it with your version, everything works correctly now. Thank you!

**Comment by agnostic-apollo** [comment]
Great, welcome.

`tsu` maintainers (@cswl) should look into this though. Possibly an issue should be opened in the repo.

https://github.com/cswl/tsu

**Comment by Minabsapi** [comment]
That's right, I will report that there
