### ISSUE TITLE
[request] shortcuts tree

### ISSUE THREAD

**Issue by FilipBB** [termux/termux-widget#7]
I think it would be useful for the shortcuts widget to be able to read shortcuts in a tree mode. So you could have a directory structure within the '.shortcuts' folder where shortcuts could be sorted into different directories.

For example:

|--.shortcuts
|    |-- ssh
|    |    |-- server1
|    |    |-- server2
|    |-- scripts
|    |    |-- python
|    |    |    |-- pythonscript1
|    |    |    |-- pythonscript2
|    |    |-- bash
|    |    |    |-- bashscript1
|    |    |    |-- bashscript2

**Comment by fornwall** [comment]
@FilipBB Thanks for the suggestion - this will be available in the v0.4 update that should be available as an update in a couple of hours.

**Comment by FilipBB** [comment]
Awesome, thanks!

**Comment by FilipBB** [comment]
Would it be possible to have the folders in the widget enterable/exitable? I.E. so only the top level would be shown, until a folder is "opened" instead of everything being listed in a tree format?
