### ISSUE TITLE
no shortcut available on Widget

### ISSUE THREAD

**Issue by skamos** [termux/termux-widget#70]
**Problem description**

I put three .sh files in the ~/.shortcuts folder, but none of them are visible in the widget app 

**Steps to reproduce**

I am not a termux expert, to know everything I followed this tutorial step by step, (only the end is useful for the report) 
https://renerocks.ai/blog/obsidian-encrypted-github-android/#git-and-git-crypt

I then tried to redo it by creating the folder as indicated in the readme:
mkdir -p /data/data/com.termux/files/home/.shortcuts
chmod 700 -R /data/data/com.termux/files/home/.shortcuts

**Expected behavior**

have access to my shortcuts with the widgets 

**Additional information**

* Termux application version: 0.118.0
* Android OS version: 11
* Device model: Fairphone 4

it may be a clue but I installed termux for the first time (without widget) on the play-store,
then after uninstalled and reinstalled by f-droid (with widget)

**Comment by agnostic-apollo** [comment]
Where in the app are you looking? You need to create a widget on launcher.

**Comment by skamos** [comment]
yes, sorry I didn't specify, but when I add the widget it tells me that the ~/.shortcuts/ folder is empty

**Comment by agnostic-apollo** [comment]
The link you shared is creating symlinks outside `~/.shortcuts` directory, that is not allowed since `v0.13.0`.

> Files under hidden directories whose name starts with a dot ., broken symlinks or files whose canonical path is not under the ~/.shortcuts or ~/.termux directory are not shown in the widget and execution is not allowed for the later either.

https://github.com/termux/termux-widget#script-directories-mandatory
