### ISSUE TITLE
can't find an icon for my script on desktop

### ISSUE THREAD

**Issue by LinuxOpa** [termux/termux-widget#71]
**Problem description**
Followed everything in the termux:widget documentation exactly
script: minifresh.sh
![1](https://user-images.githubusercontent.com/41851582/151795974-64a47efd-b4c7-45bc-856a-14a721bdbb48.jpg)
icon: minifresh.sh.png
![minifresh sh](https://user-images.githubusercontent.com/41851582/151796504-87201ac1-faac-4b38-b3c2-1278c89c1ab6.png)
my script runs fine in termux
my script runs fine in the termux:widget widget
but can't find an icon for my script on desktop
followed step by step in https://github.com/termux/termux-widget#script-icon-directory-optional

**Steps to reproduce**
see above

**Expected behavior**
an icon on desktop

**Additional information**

* Termux application version: 0.118.0
* Android OS version: 10
* Device model: Realme 6

**Comment by agnostic-apollo** [comment]
Icon is for single `Termux Shortcut`, not for `Termux Widget` list.

**Comment by LinuxOpa** [comment]
ok, where's the howto for "Icon is for single Termux Shortcut"?

**Comment by agnostic-apollo** [comment]
>You can also add a launcher shortcut for any script file with an optional custom icon as detailed in Script Icon Directory.

https://github.com/termux/termux-widget#script-directories-mandatory

In the launcher widget list, two entries should show for `termux-widget` app.
