### ISSUE TITLE
termux-open-url (am start --user 0 -a) does not work from Termux:Widget

### ISSUE THREAD

**Issue by chapmanjacobd** [termux/termux-widget#75]
**Steps to reproduce**

```sh
tee .shortcuts/tasks/test.sh
#!/bin/bash
termux-open-url http://www.google.com
```

Create a widget and click. kapow~

**Problem description**
When the created widget is clicked nothing happens except for the notification that the script ran. I'm guessing this is related to security or something. Maybe this: https://stackoverflow.com/questions/65206233/android-cant-start-an-activity-with-am-start-when-running-as-user-on-androi

**Expected behavior**
The bash script should execute the same as if it was run from the normal Termux app instance

**Additional information**
* Termux application version: 0.118.0
* Android OS version: 12 (crDroid 8.4)
* Device model: surya

**Comment by chapmanjacobd** [comment]
This is just a simple example. If my [use-case](https://github.com/chapmanjacobd/phone/blob/main/.shortcuts/tasks/links.sh) was this trivial I would just create a bookmark or something

**Comment by agnostic-apollo** [comment]
Grant termux `Draw over apps` permission.

https://github.com/termux/termux-widget/#draw-over-apps-permission-optional

**Comment by chapmanjacobd** [comment]
ah I missed that documentation. now my simple example widget is working! but my other script still isn't working... kinda strange

here is the complex widget:

https://github.com/chapmanjacobd/phone/blob/main/.shortcuts/tasks/open-browser.sh
https://github.com/chapmanjacobd/phone/blob/main/.shortcuts/tasks/links.sh

**It works when executed from the Termux window** but not for the widget--the script still runs from the widget: the sed portion of the script truncates the file but the browser does not have new tabs added

**Comment by agnostic-apollo** [comment]
Fix shebang for `open-browser`.

https://github.com/termux/termux-widget/#termux-environment
