### ISSUE TITLE
Items in widget are not clickable

### ISSUE THREAD

**Issue by laoyur** [termux/termux-widget#76]
**Problem description**

items in widget are not working, the whole widget shrinks when clicking, as if the items/button are all not clickable. please see the attached video file

https://user-images.githubusercontent.com/2039086/163915694-e32b47ec-690f-4340-9261-6639a766c905.mp4

**Steps to reproduce**

Sometimes it works, and the most of time, it does not work. I still don't know how to 100% reproduce this problem.

**Expected behavior**

make widget works

**Additional information**
Is it a rom/launcher problem?

* Termux application version: 0.118.0, widget version: 0.13.0
* Android OS version: Vivo OriginOS based on Android 12
* Device model: Vivo V2118A

**Comment by agnostic-apollo** [comment]
Try a different launcher like nova launcher.
