### ISSUE TITLE
Why does a termux:widget ~/.shortcuts script run over and over in an infinite loop?

### ISSUE THREAD

**Issue by reikred** [termux/termux-widget#87]
I wrote a little script called rsync-camera that uses rsync to backup my photo files. The script runs fine when invoked standalone from the termux terminal shell.

 However, if  run the script via  the termux:widget mechanism, it runs, asks for password (this is normal), then flashes some output, then clears the terminal and starts over again asking for the password. To me the only explanation I can come up with is that termux:widget invokes the script over and over again. I can kill it with a few attempts at Control-C, but the behavior of clearing the screen and starting over seems strange. Any ideas?

(Android 11, rooted, otherwise nothing special.)

**Comment by Grimler91** [comment]
Please share the script and your output of `termux-info`. From where have you installed termux-app and termux-widget?

**Comment by reikred** [comment]
```
#!/data/data/com.termux/files/usr/bin/bash

sudo \
RSYNC_PASSWORD=********\
/data/data/com.termux/files/usr/bin/rsync \
-uav \     
/storage/emulated/0/DCIM/Camera/ rsync://user@machine:/tmp/Camera/
```

**Comment by agnostic-apollo** [comment]
Please provide complete password, user and machine info so we can test. Thank you.

**Comment by agnostic-apollo** [comment]
Jokes apart, which `sudo` are you using?

**Comment by agnostic-apollo** [comment]
And how does script ask for password?

Also check https://github.com/termux/termux-widget#termux-environment

**Comment by Grimler91** [comment]
@reikred also doesn't look like sudo is necessary in that script, folder should be readable by normal user if you grant termux access with `termux-setup-storage`

**Comment by reikred** [comment]
@Grimler91 good suggestion, but  even with `termux-setup-storage` , there is still a weird problem. The script nopw looks as follows

```
#!/data/data/com.termux/files/usr/bin/bash

env RSYNC_PASSWORD=****** \
/data/data/com.termux/files/usr/bin/rsync \
-uav \     
/storage/emulated/0/DCIM/Camera/ rsync://user@machine:/tmp/Camera/

read -p continue?: dummy
```

The result of running he widget is

```
sending incremental file list
rsync: [sender] link_stat "/data/data/com.termux/files/home/ " failed: No such file or directory (2)

sent 19 bytes  received 12 bytes  62.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1326) [sender=3.2.4]
.shortcuts/rsyncd-camera: line 6: /storage/emulated/0/DCIM/Camera/: Is a directory
continue?:
```

(The error is the same whether I run the script via termux:widget, OR typed into termux as ~/.shortcuts/rsyncd-camera, OR typed into an ssh login.)

Does any of this make sense to you?

**Comment by Grimler91** [comment]
@reikred seems same as https://stackoverflow.com/a/18075734, i.e
 caused by space after \ on -uav line

**Comment by agnostic-apollo** [comment]
Since you are on Android 11, likely issue of permission denied is due to bug. Disable and regrant storage permission from termux app info and you shouldn't require `sudo`.

**Comment by reikred** [comment]
> Disable and regrant storage permission from termux app info and you shouldn't require `sudo`.

That fixed it, thank you.

**Comment by agnostic-apollo** [comment]
Great. Welcome.
