### ISSUE TITLE
Run shortcut in the background

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-widget#9]
This has been talked about extensively in the IRC channel and (I think) in the Google+ community. For me personally, this is a the most important feature that Termux needs. It would allow for communication between apps like Tasker and Termux. 

Examples that I would like to do:
- Launch a backup script at a certain time, location and if plugged in with Tasker (I have that, it retries if it fails for some reason. Yesterday my internet didn't work and in the morning I had to close 137 Termux sessions)
- Get the output of a command with Tasker and add it to a Zooper or Minimalistic Text widget. (Like [this](https://oliverse.ch/tech/2016/02/16/display-output-of-a-bash-script-on-a-widget.html), but without the need for a constantly running Termux loop)
- Run scripts on a [Flic ](https://flic.io/)button press

**Comment by fornwall** [comment]
Background scripts is now possible both in Termux:Widget and Termux:Task, so closing this issue.

**Comment by huangyg11** [comment]
For reference, just put the script inside ~/.shortcuts/tasks, and it will be executed background.
