### ISSUE TITLE
Widget shortcut symlinks have the wrong $0

### ISSUE THREAD

**Issue by mijofa** [termux/termux-widget#90]
**Problem description**
Widget shortcuts which are symlinks to a file in ~/.termux/ have $0 set to the symlink destination path under ~/.termux/ where $0 should really be the symlink itself.

I copied [ssh-argv0](https://manpages.debian.org/bullseye/openssh-client/ssh-argv0.1.en.html) into `~/.termux/ssh-argv0`, then symlinked to it from `~/.shortcuts/desktop` and `~/.shortcuts/server` expecting to then hit the button and SSH directly to my desktop/server accordingly, but instead I get the "This script should not be run like this, see ssh-argv0(1) for details" error that is expected when run directly as `ssh-argv0`.
This, to me, is a clear & useful usecase for doing so as I don't really want to have to create separate wrapper scripts for each system I want to SSH in to, which is my main use for that widget anyway.

**Steps to reproduce**
1. Create a script at `~/.termux/foo` which contents:
    ```
    #!/data/data/com.termux/files/usr/bin/bash
    echo "I've been run as $0"
    ```
2. Symlink to it from `~/.shortcuts/bar`
    ```
    ln -s ~/.termux/foo ~/.shortcuts/bar
    ```
3. Refresh the shortcuts widget
4. Launch `bar` from the shortcuts widget

* The newly opened terminal should then say "I've been run as foo"
* It should say "I've been run as bar"

An alternate `$TERMUX_WIDGET_ARGV0` or similar would be acceptable to me, but I don't imagine any security issues with using $0 correctly.

**Additional information**

* Termux application version: 0.118.0
* Termux:Widget application version: 0.13.0
* Android OS version: 12
* LineageOS version: 19-20221015-NIGHTLY-alioth
* Device model: Xiaomi POCO F3  "alioth"  M2012K11AG

**My findings**
I suspect this could be "fixed" by removing `.getAbsolutePath()` from [TermuxWidgetService.java#L59](https://github.com/termux/termux-widget/blob/ad155a6c484ca70bfe4ba52b8c91aa2637997a8f/app/src/main/java/com/termux/widget/TermuxWidgetService.java#L59) but I'm not at all familiar with Java/Dalvik and/or Android coding so am not at all confident in making or testing that change myself.
I don't imagine this would bring in any security vulnerabilities as it will continue to check the absolute path of the symlink before displaying it in the widget.
Theoretically there could be an issue if the symlink is updated and someone hits the widget button before the widget is refreshed, but that's already an issue anyway since the symlink's destination script could be updated in the same way.

**Comment by agnostic-apollo** [comment]
Duplicate of #59

Damn, its been an year. Will be fixed in some changes I am gonna push soon for a new release.
