### ISSUE TITLE
Feature request: tasks in subdirectories under ~/.shortcuts/tasks/ should also execute in the background

### ISSUE THREAD

**Issue by sudomain** [termux/termux-widget#93]
**Feature description**

I would like to keep my `~/.shortcuts/tasks/` more organized by making subdirectories under the tasks directory. For example, `~/.shortcuts/tasks/proot-distro/` which could contain the script `change-vnc-server-orientation.sh`. Unfortunately, my task only runs in the background if it's directly in the tasks/ directory. It runs in the foreground if it's located in `tasks/any-subdirectory/`. Please consider having scripts run in the background if they are located in any subdirectory of tasks/.

**Comment by agnostic-apollo** [comment]
Custom directory and shell runner support will be available in next version.

**Comment by agnostic-apollo** [comment]
Next version of `termux-widget`. It has already been implemented locally, but can't push it until `termux-shared` library in `termux-app` repo is pushed as well.

**Comment by sudomain** [comment]
Understood. Thank you very much for your work.

**Comment by agnostic-apollo** [comment]
You are welcome.
