### ISSUE TITLE
No widget icon 1×1

### ISSUE THREAD

**Issue by lockcher4** [termux/termux-widget#95]
No widget icon 1×1
Xiomi redmi note 10s
Miui 13

I don't know how to add an icon.
When you hold down the termux icon or termux:widget, there is also no 1x1 widget addition added.

**Comment by lockcher4** [comment]
![Screenshot_2022-12-28-20-59-02-926_com.termux.jpg](https://user-images.githubusercontent.com/105739128/209853911-588c3baf-8610-4b48-942d-71bd2b1cceee.jpg)![Screenshot_2022-12-28-20-59-02-926_com.termux.jpg](https://user-images.githubusercontent.com/105739128/209853921-ae5de863-d54b-4f94-9cf4-5ae38ceef315.jpg)

**Comment by lockcher4** [comment]
![Screenshot_2022-12-28-20-56-19-944_com.miui.home.jpg](https://user-images.githubusercontent.com/105739128/209853974-88d4bda9-e7f1-4e0c-84a3-83fcfa293bb6.jpg)![Screenshot_2022-12-28-20-59-02-926_com.termux.jpg](https://user-images.githubusercontent.com/105739128/209853982-29be1cfd-c181-44b1-93c4-d1cd92486492.jpg)

**Comment by Freed-Wu** [comment]
Looks same as #71

**Comment by agnostic-apollo** [comment]
There may be a separate list for shortcuts, if there isn't, then launcher problem. Use a different launcher.

For example openplus launcher doesn't allow it, don't know if xiaomi has similar problems.

https://www.reddit.com/r/termux/comments/ziqhgm/termuxwidget_how_to_add_shortcuts_to_homescreen/
