### ISSUE TITLE
which flag to add if the script dont need to display main termux window

### ISSUE THREAD

**Issue by Parakovsky** [termux/termux-widget#96]
first of all thank you for amazing work

i would like to setup some of my scripts that dont need visual feedback in the way that will not open the termux window after executing them from a widget if the drawing on top of other apps is enabled in permission. which is the correct way to do that?

**Comment by agnostic-apollo** [comment]
Welcome.

Read the docs https://github.com/termux/termux-widget#script-directories-mandatory
